[project]
name = "outbreak-modeling-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ehsan-suez", email = "ehsan.suez@uga.edu" }
]
requires-python = ">=3.11"
dependencies = [
    "jax>=0.10.2",
    "matplotlib>=3.11.2",
    "numpy>=2.4.6",
    "numpyro>=0.22.0",
    "pandas>=3.0.6",
]

[project.scripts]
outbreak-modeling-tutorial = "outbreak_modeling_tutorial:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
