import jax

import numpyro
import numpyro.distributions as dist

from numpyro.infer import MCMC, NUTS


# ============================================================
# BAYESIAN INFERENCE FOR R
# ============================================================
#
# Goal:
#
#     We observe epidemic data and want to infer R.
#
# Model:
#
#     R ~ LogNormal(0, 0.5)
#
#     expected_cases = R * infectiousness
#
#     observed_cases ~ Poisson(expected_cases)
#
#
# Conceptually:
#
#     prior
#       ↓
#       R
#       ↓
# epidemic model
#       ↓
# expected cases
#       ↓
# likelihood
#       ↓
# observed data
#       ↓
# posterior distribution of R
# ============================================================


# ------------------------------------------------------------
# 1. Define the probabilistic model
# ------------------------------------------------------------

def epidemic_model(
    infectiousness,
    observed_cases=None,
):
    """
    Simple probabilistic epidemic model.

    Parameters
    ----------
    infectiousness:
        Total infectiousness generated by previous cases.

    observed_cases:
        Number of cases actually observed.
    """

    # PRIOR
    #
    # Before looking at today's observed cases,
    # R is treated as uncertain.
    #
    # The LogNormal distribution guarantees R > 0.

    R = numpyro.sample(
        "R",
        dist.LogNormal(
            0.0,
            0.5,
        ),
    )

    # EPIDEMIC MODEL
    #
    # Renewal-equation relationship:
    #
    #     expected cases = R * infectiousness

    expected_cases = (
        R * infectiousness
    )

    # LIKELIHOOD
    #
    # We assume observed case counts follow a
    # Poisson distribution around expected_cases.
    #
    # obs=observed_cases tells NumPyro:
    #
    #     "This value was observed in the real data.
    #      Do not generate it as an unknown quantity."

    numpyro.sample(
        "cases",
        dist.Poisson(expected_cases),
        obs=observed_cases,
    )


# ------------------------------------------------------------
# 2. Our observed epidemic information
# ------------------------------------------------------------

infectiousness = 20.0
observed_cases = 30


# ------------------------------------------------------------
# 3. Set up NUTS
# ------------------------------------------------------------
#
# NUTS = No-U-Turn Sampler.
#
# It is a gradient-based MCMC algorithm.
#
# Remember jax.grad()?
#
# This is one place where JAX's automatic differentiation
# becomes useful underneath NumPyro.


kernel = NUTS(
    epidemic_model
)


# ------------------------------------------------------------
# 4. Create the MCMC runner
# ------------------------------------------------------------

mcmc = MCMC(
    kernel,
    num_warmup=10,
    num_samples=100,
)


# ------------------------------------------------------------
# 5. Run inference
# ------------------------------------------------------------

key = jax.random.PRNGKey(42)

mcmc.run(
    key,
    infectiousness=infectiousness,
    observed_cases=observed_cases,
)


# ------------------------------------------------------------
# 6. Print posterior results
# ------------------------------------------------------------

mcmc.print_summary()