import jax
import matplotlib.pyplot as plt
import numpy as np

import numpyro
import numpyro.distributions as dist

from numpyro.infer import MCMC, NUTS


# ============================================================
# POSTERIOR DISTRIBUTION OF R
# ============================================================
#
# We observe:
#
#     infectiousness = 20
#     cases = 30
#
# R is unknown.
#
# NumPyro will generate samples from the posterior
# distribution of R.
#
# Those samples represent values of R that are plausible
# given our prior, model, and observed data.
# ============================================================


def epidemic_model(
    infectiousness,
    observed_cases=None,
):
    """Simple probabilistic epidemic model."""

    # PRIOR:
    # R must be positive, so we use a LogNormal distribution.
    R = numpyro.sample(
        "R",
        dist.LogNormal(0.0, 0.5),
    )

    # EPIDEMIC MODEL:
    #
    # expected cases = R × infectiousness
    expected_cases = R * infectiousness

    # LIKELIHOOD:
    #
    # Observed case counts fluctuate around the
    # expected number of cases.
    numpyro.sample(
        "cases",
        dist.Poisson(expected_cases),
        obs=observed_cases,
    )


# ------------------------------------------------------------
# Observed epidemic information
# ------------------------------------------------------------

infectiousness = 20.0
observed_cases = 30


# ------------------------------------------------------------
# Run Bayesian inference
# ------------------------------------------------------------

kernel = NUTS(epidemic_model)

mcmc = MCMC(
    kernel,
    num_warmup=500,
    num_samples=1000,
)

key = jax.random.PRNGKey(42)

mcmc.run(
    key,
    infectiousness=infectiousness,
    observed_cases=observed_cases,
)


# ------------------------------------------------------------
# Extract posterior samples
# ------------------------------------------------------------
#
# get_samples() returns the values generated by MCMC.
#
# Because our unknown parameter was named "R",
# we retrieve its samples using ["R"].

posterior_samples = mcmc.get_samples()

R_samples = np.array(
    posterior_samples["R"]
)


# ------------------------------------------------------------
# Summarize posterior R
# ------------------------------------------------------------

posterior_mean = np.mean(R_samples)

lower = np.quantile(
    R_samples,
    0.025,
)

upper = np.quantile(
    R_samples,
    0.975,
)


print(
    "Posterior mean R:",
    posterior_mean,
)

print(
    "95% posterior interval:",
    lower,
    "to",
    upper,
)


# ------------------------------------------------------------
# Probability that R > 1
# ------------------------------------------------------------
#
# R > 1 corresponds to epidemic growth in our
# simplified interpretation.
#
# Because we have posterior samples, we can estimate
# this probability simply by calculating the fraction
# of samples greater than 1.

probability_R_above_1 = np.mean(
    R_samples > 1.0
)

print(
    "Posterior probability R > 1:",
    probability_R_above_1,
)


# ------------------------------------------------------------
# Plot posterior distribution
# ------------------------------------------------------------

plt.hist(
    R_samples,
    bins=30,
    density=True,
)

plt.axvline(
    1.0,
    linestyle="--",
    label="R = 1",
)

plt.axvline(
    posterior_mean,
    linestyle="--",
    label="Posterior mean",
)

plt.xlabel("R")
plt.ylabel("Density")
plt.title("Posterior Distribution of R")
plt.legend()

plt.show()