"""
Module 10 — Integrated Outbreak Model
02_infer_transmission.py

Goal
----
Take the simulated epidemic from 10.01 and infer the unknown
reproduction number R using a Bayesian renewal model in NumPyro.

The data were generated with TRUE_R = 1.4.

The inference model below does NOT receive that value.
"""

import jax.numpy as jnp
from jax import random

import numpyro
import numpyro.distributions as dist
from numpyro.infer import MCMC, NUTS


# ============================================================
# 1. OBSERVED EPIDEMIC DATA
# ============================================================
#
# These are the observations generated by 01_simulate_data.py.
#
# From the model's perspective, these are simply observed data.
# It does NOT know the R that generated them.

incidence = jnp.array(
    [
        10,
        12,
        15,
        20,
        27,
        32,
        28,
        39,
        47,
        51,
        65,
        83,
        98,
        122,
        136,
        150,
        181,
        211,
        228,
        273,
    ]
)


# Same generation-interval distribution used by the simulator.

generation_interval = jnp.array([0.2, 0.5, 0.3])


# ============================================================
# 2. CALCULATE INFECTIOUSNESS
# ============================================================
#
# For each week t:
#
# Lambda_t = sum(I_{t-s} * w_s)
#
# We can calculate Lambda_t directly from the observed
# incidence because previous incidence is known.

infectiousness = []

for week in range(3, len(incidence)):

    recent_incidence = incidence[week - 3 : week][::-1]

    lambda_t = jnp.dot(
        recent_incidence,
        generation_interval,
    )

    infectiousness.append(lambda_t)


infectiousness = jnp.array(infectiousness)


# Observations corresponding to those infectiousness values.
#
# Weeks 0-2 provided the initial history.
# Therefore inference begins at week 3.

observed_incidence = incidence[3:]


# ============================================================
# 3. DEFINE THE BAYESIAN RENEWAL MODEL
# ============================================================

def renewal_model(infectiousness, observed=None):

    # --------------------------------------------------------
    # PRIOR FOR R
    # --------------------------------------------------------
    #
    # R must be positive, so a LogNormal prior is convenient.
    #
    # Importantly:
    #
    # We do NOT tell NumPyro that the true value was 1.4.

    R = numpyro.sample(
        "R",
        dist.LogNormal(0.0, 0.5),
    )


    # --------------------------------------------------------
    # RENEWAL EQUATION
    # --------------------------------------------------------
    #
    # Expected incidence:
    #
    # mu_t = R * Lambda_t

    expected_incidence = R * infectiousness


    # --------------------------------------------------------
    # LIKELIHOOD
    # --------------------------------------------------------
    #
    # Observed incidence is assumed to follow:
    #
    # I_t ~ Poisson(R * Lambda_t)

    numpyro.sample(
        "incidence",
        dist.Poisson(expected_incidence),
        obs=observed,
    )


# ============================================================
# 4. RUN BAYESIAN INFERENCE
# ============================================================
#
# NUTS uses JAX automatic differentiation underneath.
#
# This connects:
#
# Module 04 -> JAX
# Module 05 -> NumPyro
# Module 02 -> renewal equation

kernel = NUTS(renewal_model)

mcmc = MCMC(
    kernel,
    num_warmup=500,
    num_samples=1000,
)


# JAX uses explicit random-number keys.

rng_key = random.PRNGKey(42)


mcmc.run(
    rng_key,
    infectiousness=infectiousness,
    observed=observed_incidence,
)


# ============================================================
# 5. EXAMINE THE POSTERIOR
# ============================================================

samples = mcmc.get_samples()

R_samples = samples["R"]


posterior_mean = jnp.mean(R_samples)

lower = jnp.quantile(R_samples, 0.025)
upper = jnp.quantile(R_samples, 0.975)

prob_above_one = jnp.mean(R_samples > 1.0)


print()
print("Posterior inference for R")
print("-------------------------")

print(f"Posterior mean: {posterior_mean:.3f}")

print(
    f"95% credible interval: "
    f"[{lower:.3f}, {upper:.3f}]"
)

print(
    f"P(R > 1): {prob_above_one:.3f}"
)


# ============================================================
# 6. FOR LEARNING ONLY: REVEAL THE ANSWER
# ============================================================
#
# The inference model never used this value.
#
# We reveal it only now so we can check whether our inference
# recovered the parameter used by the simulator.

TRUE_R = 1.4

print()
print(f"True R used by simulator: {TRUE_R}")