import numpy as np


# --------------------------------------------------
# Model settings
# --------------------------------------------------

R_t = 1.2

generation_interval = np.array([0.2, 0.5, 0.3])

n_days = 30

# Reproducible random-number generator.
rng = np.random.default_rng(seed=42)


# --------------------------------------------------
# Initialize incidence
# --------------------------------------------------

# Unlike the deterministic model, incidence will now
# contain integer infection counts.
incidence = np.zeros(n_days, dtype=int)

# Initial epidemic history.
incidence[0:3] = [10, 10, 10]


# --------------------------------------------------
# Stochastic renewal simulation
# --------------------------------------------------

for t in range(3, n_days):

    # Obtain incidence from 1, 2, and 3 days ago.
    past_incidence = incidence[t - 3:t][::-1]

    # Calculate total infectiousness generated by
    # previous infections.
    infectiousness = (
        past_incidence * generation_interval
    ).sum()

    # Expected incidence according to the
    # renewal equation.
    expected_incidence = R_t * infectiousness

    # Instead of setting incidence equal to its expectation,
    # draw the actual number of infections from a
    # Poisson distribution.
    incidence[t] = rng.poisson(
        lam=expected_incidence
    )


# --------------------------------------------------
# Display results
# --------------------------------------------------

for day, infections in enumerate(incidence):
    print(
        f"Day {day}: "
        f"{infections} infections"
    )