import jax


# ============================================================
# JAX AUTOMATIC DIFFERENTIATION
# ============================================================
#
# One of JAX's most important capabilities is automatic
# differentiation.
#
# This means JAX can calculate derivatives of functions
# directly from the code that defines those functions.
#
# This becomes especially useful later when we use NumPyro,
# because gradient-based Bayesian inference methods such as
# HMC and NUTS need derivatives of log probabilities.
# ============================================================


# ------------------------------------------------------------
# 1. A simple mathematical example
# ------------------------------------------------------------

def loss_function(R):
    """
    A simple toy loss function.

    The loss is minimized when R = 1.5.

        f(R) = (R - 1.5)^2
    """

    return (R - 1.5) ** 2


# Choose a value of R at which to evaluate the function.
R = 2.0

loss = loss_function(R)

print("R:", R)
print("Loss:", loss)


# ------------------------------------------------------------
# 2. Calculate the derivative automatically
# ------------------------------------------------------------
#
# Mathematically:
#
#     f(R) = (R - 1.5)^2
#
# Therefore:
#
#     f'(R) = 2(R - 1.5)
#
# At R = 2:
#
#     f'(2) = 2(2 - 1.5)
#           = 1
#
# Instead of manually writing that derivative,
# we ask JAX to create it for us.


gradient_function = jax.grad(loss_function)

gradient = gradient_function(R)

print("Gradient:", gradient)


# ------------------------------------------------------------
# 3. Epidemic-model example
# ------------------------------------------------------------
#
# Now connect automatic differentiation to something
# epidemiologically meaningful.
#
# Recall the renewal equation:
#
#     I_t = R_t * Lambda_t
#
# where:
#
#     I_t      = expected incidence
#     R_t      = reproduction number
#     Lambda_t = infectiousness generated by past incidence


def expected_cases(R_t, infectiousness):
    """
    Calculate expected incidence from a simple
    renewal-equation relationship.

        expected incidence = R_t * infectiousness
    """

    return R_t * infectiousness


R_t = 1.2
infectiousness = 19.0

cases = expected_cases(
    R_t,
    infectiousness,
)

print("\nExpected cases:", cases)


# ------------------------------------------------------------
# 4. Differentiate incidence with respect to R_t
# ------------------------------------------------------------
#
# Because R_t is the FIRST argument of expected_cases(),
# jax.grad() differentiates with respect to R_t by default.
#
# Mathematically:
#
#     I_t = R_t * Lambda_t
#
# therefore:
#
#     dI_t / dR_t = Lambda_t
#
# Since Lambda_t = 19, we expect the derivative to be 19.


cases_gradient_function = jax.grad(
    expected_cases
)

sensitivity_to_R = cases_gradient_function(
    R_t,
    infectiousness,
)

print(
    "Sensitivity to R_t:",
    sensitivity_to_R,
)


# ------------------------------------------------------------
# 5. Interpret the gradient
# ------------------------------------------------------------
#
# A derivative describes how sensitive the output is
# to a small change in a parameter.
#
# Here:
#
#     dI_t / dR_t = 19
#
# So approximately:
#
#     change in incidence
#       ≈ gradient * change in R_t
#
# If R_t increases by 0.01:
#
#     change ≈ 19 * 0.01
#            = 0.19


small_change_in_R = 0.01

approximate_change_in_cases = (
    sensitivity_to_R
    * small_change_in_R
)

print(
    "\nIf R_t increases by",
    small_change_in_R,
)

print(
    "Approximate increase in expected cases:",
    approximate_change_in_cases,
)

#0.01 increase in R approximately 0.19 increase in expected cases
#that's easy interpretation
# ------------------------------------------------------------
# Main takeaway
# ------------------------------------------------------------
#
# jax.grad(function)
#
# takes a function and RETURNS ANOTHER FUNCTION that
# calculates its derivative.
#
# We did NOT manually program:
#
#     2 * (R - 1.5)
#
# or:
#
#     infectiousness
#
# JAX obtained those derivatives from the original
# mathematical code.
#
# Later, our functions will be much more complicated:
#
# parameters
#      ↓
# epidemic model
#      ↓
# probability model
#      ↓
# likelihood
#      ↓
# posterior inference
#
# JAX can propagate derivatives through those calculations,
# which is one reason it is so useful underneath NumPyro.